//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatieAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_District
    {
        public tbl_District()
        {
            this.tbl_Shop = new HashSet<tbl_Shop>();
        }
    
        public int id_district { get; set; }
        public string district { get; set; }
    
        public virtual ICollection<tbl_Shop> tbl_Shop { get; set; }
    }
}
