//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatieAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Shop
    {
        public tbl_Shop()
        {
            this.tbl_Comment = new HashSet<tbl_Comment>();
            this.tbl_Image = new HashSet<tbl_Image>();
            this.tbl_Rate = new HashSet<tbl_Rate>();
        }
    
        public int id_shop { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public int id_district { get; set; }
        public int id_food { get; set; }
        public string description { get; set; }
        public Nullable<double> price_medium { get; set; }
        public Nullable<double> time_medium { get; set; }
        public bool isDelete { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public double averageRate { get; set; }
    
        public virtual ICollection<tbl_Comment> tbl_Comment { get; set; }
        public virtual tbl_District tbl_District { get; set; }
        public virtual ICollection<tbl_Image> tbl_Image { get; set; }
        public virtual tbl_Main_Course tbl_Main_Course { get; set; }
        public virtual ICollection<tbl_Rate> tbl_Rate { get; set; }
    }
}
