//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatieProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Image
    {
        public int id_img { get; set; }
        public int id_shop { get; set; }
        public string url_image { get; set; }
        public bool isDelete { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        public virtual tbl_Shop tbl_Shop { get; set; }
    }
}
